In [2]:
import pandas as pd
df = pd.read_csv('../house_data.csv', index_col=0)

In [3]:
df.head()

,標題,产权性质,住宅类别,建筑类别,参考月供,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,NaN,1989年,70.40,2室2厅1厨1卫,中层(共6层),暂无资料,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,NaN,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0
3,精装二房全明户型户型好客厅主卧朝南带阳台看房方便,商品房,NaN,板楼,NaN,1994年,56.00,2室1厅1厨1卫,高层(共6层),0.4元/平米・月,住宅,平层,简装修,280.0
4,"满五税费少,房东接受置换客户,房东这边房子已经看好,急卖",个人产权,普通住宅,钢混,NaN,1998年,58.00,2室1厅1厨1卫,高层(共6层),0.4元/平米・月,住宅,平层,精装修,190.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 240 entries, 0 to 239
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   標題      240 non-null    object
 1   产权性质    228 non-null    object
 2   住宅类别    218 non-null    object
 3   建筑类别    188 non-null    object
 4   参考月供    0 non-null      float64
 5   年代      224 non-null    object
 6   建筑面积    240 non-null    float64
 7   户型      240 non-null    object
 8   楼层      228 non-null    object
 9   物 业 费   240 non-null    object
 10  物业类型    240 non-null    object
 11  结构      181 non-null    object
 12  装修      228 non-null    object
 13  總價      237 non-null    float64
dtypes: float64(3), object(11)
memory usage: 28.1+ KB

In [5]:
df.isnull().sum()

標題         0
产权性质      12
住宅类别      22
建筑类别      52
参考月供     240
年代        16
建筑面积       0
户型         0
楼层        12
物 业 费      0
物业类型       0
结构        59
装修        12
總價         3
dtype: int64

In [11]:
import numpy as np
df.loc[df['物 业 费'] == '暂无资料', '物 业 费'] = np.nan

In [12]:
df.head()

,標題,产权性质,住宅类别,建筑类别,参考月供,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,NaN,1989年,70.40,2室2厅1厨1卫,中层(共6层),NaN,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,NaN,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0
3,精装二房全明户型户型好客厅主卧朝南带阳台看房方便,商品房,NaN,板楼,NaN,1994年,56.00,2室1厅1厨1卫,高层(共6层),0.4元/平米・月,住宅,平层,简装修,280.0
4,"满五税费少,房东接受置换客户,房东这边房子已经看好,急卖",个人产权,普通住宅,钢混,NaN,1998年,58.00,2室1厅1厨1卫,高层(共6层),0.4元/平米・月,住宅,平层,精装修,190.0

In [14]:
df.columns

Index(['標題', '产权性质', '住宅类别', '建筑类别', '参考月供', '年代', '建筑面积', '户型', '楼层', '物 业 费',
       '物业类型', '结构', '装修', '總價'],
      dtype='object')

In [16]:
df = df.drop('参考月供', axis=1)

In [17]:
df.head()

,標題,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,1989年,70.40,2室2厅1厨1卫,中层(共6层),NaN,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0
3,精装二房全明户型户型好客厅主卧朝南带阳台看房方便,商品房,NaN,板楼,1994年,56.00,2室1厅1厨1卫,高层(共6层),0.4元/平米・月,住宅,平层,简装修,280.0
4,"满五税费少,房东接受置换客户,房东这边房子已经看好,急卖",个人产权,普通住宅,钢混,1998年,58.00,2室1厅1厨1卫,高层(共6层),0.4元/平米・月,住宅,平层,精装修,190.0

In [19]:
df[(df['建筑面积']>100) & (df['總價'] > 2000) ].head()

,標題,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0
11,绿城豪宅，精品纯独栋，格局方正，双南设计，全明通透，豪华气派,NaN,NaN,NaN,NaN,502.00,5室3厅2厨6卫,NaN,6.5元/平方米・月,别墅,NaN,NaN,2798.0
60,华府天地主营专员+价格可谈+1层1户+看房方便+送车位+高区看湖景,个人产权,普通住宅,NaN,2006年,454.82,5室3厅2厨4卫,高层(共21层),14.5元/平米・月,住宅,NaN,精装修,5500.0
82,央企品质！厅南北通卧室全南！一线看江！带车位,个人产权,普通住宅,NaN,1900年,186.88,3室2厅0厨2卫,中层(共25层),7.7元/・月,住宅,NaN,中装修,2500.0
103,每一座传世尊邸稀若上天恩赐。。此房仅献给少数人中的少数,NaN,NaN,NaN,NaN,558.00,6室3厅1厨5卫,NaN,5.95元/平米・月,别墅,NaN,NaN,2780.0

In [31]:
df.rename(columns={'物 业 费': '物业费'}, inplace=True)

In [34]:
df.head()

,标题,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物业费,物业类型,结构,装修,总价
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,1989年,70.40,2室2厅1厨1卫,中层(共6层),0,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0
3,精装二房全明户型户型好客厅主卧朝南带阳台看房方便,商品房,NaN,板楼,1994年,56.00,2室1厅1厨1卫,高层(共6层),0.4元/平米・月,住宅,平层,简装修,280.0
4,"满五税费少,房东接受置换客户,房东这边房子已经看好,急卖",个人产权,普通住宅,钢混,1998年,58.00,2室1厅1厨1卫,高层(共6层),0.4元/平米・月,住宅,平层,精装修,190.0

In [33]:
df['物业费'] = df['物业费'].fillna(0)

In [35]:
df['总价'].isnull().sum()

3

In [37]:
df[df['总价'].isnull()]

,标题,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物业费,物业类型,结构,装修,总价
18,光新路191弄 南北通透两室户 地段佳 出行方便满五少税,个人产权,普通住宅,板楼,1990年,47.00,2室1厅1厨1卫,低层(共6层),0.3元/平米・月,住宅,平层,精装修,NaN
160,周边六所 高铁旁 风景边 别墅生活圈 户型,商品房,普通住宅,钢混,2013年,90.00,3室1厅1厨1卫,中层(共18层),0,住宅,平层,豪华装修,NaN
175,精品好房 稍纵即逝,个人产权,普通住宅,钢混,2014年,99.38,3室2厅1厨2卫,中层(共11层),1.95元/・月,住宅,平层,精装修,NaN

In [38]:
df['总价'].fillna(df['建筑面积']*(df['总价']/df['建筑面积']).mean(), inplace=True)

In [39]:
df['总价'].isnull().sum()

0

In [40]:
df.to_csv('../house_final.csv', index_label=False)

In [46]:
df = pd.read_excel('../house_sample.xlsx')
df.head()

,Unnamed: 0,标题,建筑面积,总价,户型,朝向,物 业 费,环比上月,张贴日期,产权性质,装修,楼层
0,0,资深经纪上海人：稀缺3房，南北通透采光好，房东急需用钱！,123.50,760,3室2厅0厨2卫,南北,1.5元/平米・月,↑1.44%,西元2017年4月12日,商品房,豪华装修,低层
1,1,未来规划小上海，精装带地暖，养老，亲子，旅游度假一体化,86.00,76,2室2厅1厨1卫,南北,1.8元/・月,↑4.08%,西元2017年4月13日,商品房,精装修,中层
2,2,双高铁 不限贷 买一层送一层 送大露台 看房专车接送,90.00,80,3室2厅1厨2卫,南北,暂无资料,↓0.01%,西元2017年4月14日,商品房,精装修,高层
3,3,坐拥嘉兴海宁双轨 享受市区配套 现房值得拥有 可落户,90.00,80,2室1厅1厨1卫,南北,暂无资料,↓0.01%,西元2017年4月15日,商品房,简装修,中层
4,4,对口明强校区，精装两房税费少，位置安静，媲美园艺新村，随时看,66.61,285,2室1厅1厨1卫,南,0.8元/平米・月,↓2.62%,西元2017年4月16日,个人产权,中装修,低层

In [48]:
df.rename(columns={'物 业 费': '物业费'}, inplace=True)
df.loc[df['物业费'] == '暂无资料', '物业费'] = np.nan

In [49]:
df.head()

,Unnamed: 0,标题,建筑面积,总价,户型,朝向,物业费,环比上月,张贴日期,产权性质,装修,楼层
0,0,资深经纪上海人：稀缺3房，南北通透采光好，房东急需用钱！,123.50,760,3室2厅0厨2卫,南北,1.5元/平米・月,↑1.44%,西元2017年4月12日,商品房,豪华装修,低层
1,1,未来规划小上海，精装带地暖，养老，亲子，旅游度假一体化,86.00,76,2室2厅1厨1卫,南北,1.8元/・月,↑4.08%,西元2017年4月13日,商品房,精装修,中层
2,2,双高铁 不限贷 买一层送一层 送大露台 看房专车接送,90.00,80,3室2厅1厨2卫,南北,NaN,↓0.01%,西元2017年4月14日,商品房,精装修,高层
3,3,坐拥嘉兴海宁双轨 享受市区配套 现房值得拥有 可落户,90.00,80,2室1厅1厨1卫,南北,NaN,↓0.01%,西元2017年4月15日,商品房,简装修,中层
4,4,对口明强校区，精装两房税费少，位置安静，媲美园艺新村，随时看,66.61,285,2室1厅1厨1卫,南,0.8元/平米・月,↓2.62%,西元2017年4月16日,个人产权,中装修,低层

In [51]:
df['张贴日期'] = pd.to_datetime(df['张贴日期'], format='西元%Y年%m月%d日')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  29 non-null     int64
 1   标题          29 non-null     object
 2   建筑面积        29 non-null     float64
 3   总价          29 non-null     int64
 4   户型          29 non-null     object
 5   朝向          29 non-null     object
 6   物业费         25 non-null     object
 7   环比上月        29 non-null     object
 8   张贴日期        29 non-null     datetime64[ns]
 9   产权性质        29 non-null     object
 10  装修          29 non-null     object
 11  楼层          29 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(2), object(8)
memory usage: 2.8+ KB

In [53]:
df[['室', '厅', '厨', '卫']] = df['户型'].str.extract('(\d+)室(\d+)厅(\d+)厨(\d+)卫', expand=False)

In [54]:
df.head()

,Unnamed: 0,标题,建筑面积,总价,户型,朝向,物业费,环比上月,张贴日期,产权性质,装修,楼层,室,厅,厨,卫
0,0,资深经纪上海人：稀缺3房，南北通透采光好，房东急需用钱！,123.50,760,3室2厅0厨2卫,南北,1.5元/平米・月,↑1.44%,2017-04-12,商品房,豪华装修,低层,3,2,0,2
1,1,未来规划小上海，精装带地暖，养老，亲子，旅游度假一体化,86.00,76,2室2厅1厨1卫,南北,1.8元/・月,↑4.08%,2017-04-13,商品房,精装修,中层,2,2,1,1
2,2,双高铁 不限贷 买一层送一层 送大露台 看房专车接送,90.00,80,3室2厅1厨2卫,南北,NaN,↓0.01%,2017-04-14,商品房,精装修,高层,3,2,1,2
3,3,坐拥嘉兴海宁双轨 享受市区配套 现房值得拥有 可落户,90.00,80,2室1厅1厨1卫,南北,NaN,↓0.01%,2017-04-15,商品房,简装修,中层,2,1,1,1
4,4,对口明强校区，精装两房税费少，位置安静，媲美园艺新村，随时看,66.61,285,2室1厅1厨1卫,南,0.8元/平米・月,↓2.62%,2017-04-16,个人产权,中装修,低层,2,1,1,1